# =============================================================================
# SentinentalBERT Docker Compose Configuration
# =============================================================================
#
# OVERVIEW:
# This Docker Compose file defines the complete SentinentalBERT platform
# architecture with all necessary services for local development and testing.
# It includes databases, message queues, application services, and monitoring.
#
# SERVICES INCLUDED:
# - PostgreSQL: Primary database for structured data storage
# - Elasticsearch: Full-text search and analytics engine
# - Redis: Caching and session management
# - Kafka + Zookeeper: Message streaming and event processing
# - NLP Service: Python-based sentiment analysis and ML processing
# - Backend Service: Java Spring Boot API and business logic
# - Ingestion Service: Rust-based high-performance data collection
# - Frontend: React-based user interface
# - Monitoring: Prometheus, Grafana, and Jaeger for observability
# - Nginx: Reverse proxy and load balancer
#
# USAGE:
# - Development: docker-compose up -d
# - Production: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
# - With GPU: docker-compose -f docker-compose.yml -f docker-compose.gpu.yml up -d
# - Minimal: docker-compose -f docker-compose.yml -f docker-compose.minimal.yml up -d
#
# PRIVACY & SECURITY:
# - All services are configured with security best practices
# - Passwords and secrets are managed via environment variables
# - Network isolation using custom bridge network
# - Health checks ensure service reliability
# - Resource limits prevent resource exhaustion
#
# LEGAL COMPLIANCE:
# - GDPR-compliant data processing configurations
# - Audit logging enabled for all services
# - Data retention policies configured
# - Privacy-preserving analytics settings
#
# Author: SentinentalBERT Team
# License: MIT License with Privacy Compliance Addendum
# Version: 1.0.0
# Last Updated: 2024-01-15
# =============================================================================

# Docker Compose file format version
# Version 3.8 supports all features needed for production deployment
version: '3.8'

services:
  # =============================================================================
  # DATABASE SERVICES
  # =============================================================================
  # These services provide persistent data storage for the application
  
  # PostgreSQL Database Service
  # Primary relational database for storing structured data including:
  # - User accounts and authentication data
  # - Social media posts and metadata
  # - Analysis results and sentiment scores
  # - System configuration and audit logs
  postgres:
    image: postgres:15
    container_name: sentinelbert-postgres
    environment:
      POSTGRES_DB: sentinelbert
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sentinel123}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - sentinelbert-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentinel -d sentinelbert"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:8.10.0
    container_name: sentinelbert-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - sentinelbert-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: sentinelbert-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis123}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - sentinelbert-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Message Queue
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: sentinelbert-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_logs:/var/lib/zookeeper/log
    networks:
      - sentinelbert-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: sentinelbert-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    volumes:
      - kafka_data:/var/lib/kafka/data
    ports:
      - "9092:9092"
    networks:
      - sentinelbert-network
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Application Services
  ingestion-service:
    build:
      context: ./services/ingestion
      dockerfile: Dockerfile
    container_name: sentinelbert-ingestion
    environment:
      - DATABASE_URL=postgresql://sentinel:${POSTGRES_PASSWORD:-sentinel123}@postgres:5432/sentinelbert
      - REDIS_URL=redis://:${REDIS_PASSWORD:-redis123}@redis:6379
      - KAFKA_BROKERS=kafka:29092
      - RUST_LOG=info
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      - INSTAGRAM_ACCESS_TOKEN=${INSTAGRAM_ACCESS_TOKEN}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - sentinelbert-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  nlp-service:
    build:
      context: ./services/nlp
      dockerfile: Dockerfile
    container_name: sentinelbert-nlp
    environment:
      - MODEL_PATH=/app/models
      - REDIS_URL=redis://:${REDIS_PASSWORD:-redis123}@redis:6379
      - DATABASE_URL=postgresql://sentinel:${POSTGRES_PASSWORD:-sentinel123}@postgres:5432/sentinelbert
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./models:/app/models:ro
      - nlp_cache:/app/cache
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - sentinelbert-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  backend-service:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: sentinelbert-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sentinelbert
      - SPRING_DATASOURCE_USERNAME=sentinel
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-sentinel123}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD:-redis123}
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - NLP_SERVICE_URL=http://nlp-service:8000
      - INGESTION_SERVICE_URL=http://ingestion-service:8080
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here}
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
      nlp-service:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - sentinelbert-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sentinelbert-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - REACT_APP_WEBSOCKET_URL=ws://localhost:8080
      - REACT_APP_VERSION=1.0.0
    depends_on:
      - backend-service
    ports:
      - "3000:80"
    networks:
      - sentinelbert-network
    restart: unless-stopped

  # Monitoring Services
  prometheus:
    image: prom/prometheus:latest
    container_name: sentinelbert-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - sentinelbert-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: sentinelbert-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin123}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3001:3000"
    networks:
      - sentinelbert-network
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: sentinelbert-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14268:14268"
    networks:
      - sentinelbert-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: sentinelbert-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend-service
    networks:
      - sentinelbert-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  elasticsearch_data:
    driver: local
  redis_data:
    driver: local
  kafka_data:
    driver: local
  zookeeper_data:
    driver: local
  zookeeper_logs:
    driver: local
  nlp_cache:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  sentinelbert-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16