apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentinelbert-ingestion-service
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "50"
        autoscaling.knative.dev/minScale: "0"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 900
      serviceAccountName: sentinelbert-ingestion-dev@PROJECT_ID.iam.gserviceaccount.com
      containers:
      - image: gcr.io/PROJECT_ID/sentinelbert-ingestion:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: GCP_PROJECT
          value: "PROJECT_ID"
        - name: ENVIRONMENT
          value: "dev"
        - name: PUBSUB_TOPIC
          value: "social-media-raw-dev"
        - name: STORAGE_BUCKET
          value: "PROJECT_ID-sentinelbert-raw-data-dev"
        - name: RUST_LOG
          value: "info"
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true